
title: My Resume
url: 'https://github.com'
baseurl: '/nthakur20.github.io' #change it according to your repository name



# Profile information
yourname: Nandan Thakur  ## put your name
title: 'DATA SCIENTIST'  ## your title
location: Bangalore, India


## Social Profiles
facebook: http://www.facebook.com/nandan.thakur.7  ## your facebook account url
twitter: http://www.twitter.com/Nthakur20  ## your twitter account url
linkedin: http://www.linkedin.com/in/nthakur20/  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
